-- Productos iniciales del catalogo CDP Wheels
-- Ejecutar despues de schema.sql y migrations-2026.sql

USE cdp_wheels;

INSERT INTO productos (slug, marca, marca_filtro, modelo, modelo_filtro, nombre, descripcion, descripcion_corta, material, color, habilitar_color_detalle, precio, precio_anterior, etiqueta, valoracion, imagen_principal, galeria, acabados, compatibilidad, especificaciones, tags, stock, activo) VALUES
(
  'bmw-f80-f82-cuero-alcantara-rojo-sport',
  'BMW',
  'bmw',
  'F80 / F82',
  'f80-f82',
  'Volante BMW M3 / M4 Cuero Alcantara Sport',
  'Volante personalizado para BMW M3 F80 y M4 F82 con base en cuero perforado y secciones de alcantara en los agarres laterales. Costuras en rojo deportivo a contraste, marcador superior tricolor M y embellecedores en negro mate. Incluye levas magneticas en carbono brillante. Producto fabricado a medida en taller propio en Vizcaya.',
  'Volante M3/M4 con cuero perforado, alcantara y costuras rojas. Levas magneticas en carbono.',
  'Cuero perforado + Alcantara',
  'Negro / Rojo',
  1,
  749.00,
  890.00,
  'Mas vendido',
  '4.9',
  'assets/img/gallery/F82/cuero_alcantara_rojo/principal.png',
  '["assets/img/gallery/F82/cuero_alcantara_rojo/principal.png","assets/img/gallery/F82/cuero_alcantara_rojo/lateral.png","assets/img/gallery/F82/cuero_alcantara_rojo/vista_x2.png"]',
  '["Cuero perforado napa","Alcantara premium","Costuras rojas","Carbono brillante"]',
  '["BMW M3 F80","BMW M4 F82","BMW M2 F87"]',
  '{"aro":"Cuero perforado","agarres":"Alcantara","costuras":"Rojo deportivo","marcador":"Tricolor M","levas":"Magneticas carbono","pantalla_rpm":"No"}',
  'bmw,m3,m4,f80,f82,m2,f87,cuero,alcantara,rojo,sport,carbono',
  3,
  1
),
(
  'bmw-e46-cuero-azul-achatado',
  'BMW',
  'bmw',
  'E46',
  'e46',
  'Volante BMW E46 Cuero Achatado con Tira Azul',
  'Volante para BMW Serie 3 E46 con diseno achatado en la parte inferior. Base en cuero liso negro con una tira central en azul racing recoloreable a tu gusto. Costuras en blanco y marcador superior tricolor M discreto. Una opcion clasica con un toque deportivo, ideal para coches preparados o restomod.',
  'Volante E46 achatado abajo, cuero negro con tira azul recoloreable. Costuras blancas, marcador M.',
  'Cuero liso',
  'Negro / Azul',
  1,
  549.00,
  NULL,
  'Disenado en CDP',
  '4.8',
  'assets/img/gallery/E46/Cuero_azul_achatado/principal.jpeg',
  '["assets/img/gallery/E46/Cuero_azul_achatado/principal.jpeg","assets/img/gallery/E46/Cuero_azul_achatado/lateral.jpeg","assets/img/gallery/E46/Cuero_azul_achatado/vista_x2.jpeg"]',
  '["Cuero liso napa","Tira de color personalizable","Costura blanca","Achatado inferior"]',
  '["BMW Serie 3 E46","BMW M3 E46"]',
  '{"aro":"Cuero liso","agarres":"Cuero liso","costuras":"Blanco","marcador":"Tricolor M","levas":"Sin levas","pantalla_rpm":"No","extra":"Achatado parte inferior"}',
  'bmw,e46,serie-3,m3,cuero,azul,achatado,restomod,clasico',
  5,
  1
),
(
  'audi-rs3-cuero-blanco-sport',
  'Audi',
  'audi',
  'RS3',
  'rs3',
  'Volante Audi RS3 Cuero Blanco con Marcador 12',
  'Volante deportivo para Audi RS3 (8V y 8Y) con base de cuero blanco perforado, marcador central en posicion 12 en rojo Audi Sport y costuras en gris perla. Diseno limpio, racing y elegante. Incluye levas en aluminio cepillado y pantalla RPM lateral. Producto a medida, fabricado bajo pedido en CDP Wheels.',
  'Volante RS3 cuero blanco con marcador rojo, levas aluminio y pantalla RPM lateral.',
  'Cuero perforado',
  'Blanco / Rojo',
  0,
  879.00,
  NULL,
  'Nuevo',
  '4.9',
  'assets/img/gallery/RS3/cuero rs blanco/foto principal.png',
  '["assets/img/gallery/RS3/cuero rs blanco/foto principal.png"]',
  '["Cuero perforado","Marcador central 12","Pantalla RPM","Levas aluminio cepillado"]',
  '["Audi RS3 8V","Audi RS3 8Y","Audi S3 8V","Audi S3 8Y"]',
  '{"aro":"Cuero perforado","agarres":"Cuero perforado","costuras":"Gris perla","marcador":"Rojo Audi Sport","levas":"Aluminio cepillado","pantalla_rpm":"Si"}',
  'audi,rs3,s3,8v,8y,cuero,blanco,sport,levas-aluminio,rpm',
  2,
  1
),
(
  'mercedes-amg-cuero-alcantara-performance',
  'Mercedes',
  'mercedes',
  'AMG',
  'amg',
  'Volante Mercedes AMG Performance Cuero Alcantara',
  'Volante personalizado para Mercedes-AMG (modelos A45, C63, E63, GLA45) con base de cuero napa en los agarres laterales y zona central en alcantara negra. Costuras dobles en plata AMG y marcador superior amarillo Performance. Acabados en carbono brillante en los radios y levas en aluminio negro. Producto fabricado a medida con materiales certificados.',
  'Volante AMG con cuero, alcantara y costuras plata. Marcador amarillo Performance y radios en carbono.',
  'Cuero napa + Alcantara',
  'Negro / Plata',
  0,
  929.00,
  1050.00,
  'AMG Edition',
  '4.9',
  'assets/img/gallery/AMG/centrada.jpeg',
  '["assets/img/gallery/AMG/centrada.jpeg","assets/img/gallery/AMG/LATERAL.jpeg","assets/img/gallery/AMG/cortada.jpeg"]',
  '["Cuero napa","Alcantara","Costuras dobles plata","Carbono brillante"]',
  '["Mercedes A45 AMG","Mercedes C63 AMG","Mercedes E63 AMG","Mercedes GLA45 AMG"]',
  '{"aro":"Cuero napa","agarres":"Alcantara","costuras":"Plata AMG","marcador":"Amarillo Performance","levas":"Aluminio negro","pantalla_rpm":"No"}',
  'mercedes,amg,a45,c63,e63,gla45,cuero,alcantara,carbono,performance',
  2,
  1
),
(
  'bmw-f80-f82-carbono-alcantara-rpm',
  'BMW',
  'bmw',
  'F80 / F82',
  'f80-f82',
  'Volante BMW M3 / M4 Carbono Alcantara con Pantalla RPM',
  'Top de gama para BMW M3 F80 y M4 F82. Aro completo en carbono brillante con secciones de alcantara en los agarres y pantalla RPM integrada en la zona superior. Marcador tricolor M, costuras blancas y levas magneticas en carbono forjado. Pensado para los que buscan la version mas racing del volante CDP.',
  'F82 carbono + alcantara con pantalla RPM integrada. Levas magneticas en carbono forjado.',
  'Carbono + Alcantara',
  'Negro / Carbono',
  0,
  1190.00,
  1390.00,
  'Top de gama',
  '5.0',
  'assets/img/gallery/F82/Carbono_alcantara_rpm/Principal.png',
  '["assets/img/gallery/F82/Carbono_alcantara_rpm/Principal.png","assets/img/gallery/F82/Carbono_alcantara_rpm/lateral.png","assets/img/gallery/F82/Carbono_alcantara_rpm/vistax2.png"]',
  '["Carbono brillante","Alcantara","Pantalla RPM","Carbono forjado"]',
  '["BMW M3 F80","BMW M4 F82","BMW M2 F87"]',
  '{"aro":"Carbono brillante","agarres":"Alcantara","costuras":"Blanco","marcador":"Tricolor M","levas":"Magneticas carbono","pantalla_rpm":"Si"}',
  'bmw,m3,m4,f80,f82,carbono,alcantara,rpm,magneticas,racing,top',
  2,
  1
),
(
  'bmw-f80-f82-carbono-cuero',
  'BMW',
  'bmw',
  'F80 / F82',
  'f80-f82',
  'Volante BMW M3 / M4 Carbono y Cuero',
  'Volante deportivo para BMW M3 F80 y M4 F82 con aro en carbono brillante combinado con cuero napa en los agarres laterales. Costuras en color a elegir, marcador superior tricolor M y levas en aluminio cepillado. Diseno elegante y agresivo al mismo tiempo, ideal para uso diario.',
  'F82 con aro de carbono y cuero napa. Costuras a elegir y levas de aluminio.',
  'Carbono + Cuero napa',
  'Negro',
  0,
  890.00,
  NULL,
  'Mas vendido',
  '4.9',
  'assets/img/gallery/F82/Carbono_cuero/pricipal.png',
  '["assets/img/gallery/F82/Carbono_cuero/pricipal.png","assets/img/gallery/F82/Carbono_cuero/lateral.png","assets/img/gallery/F82/Carbono_cuero/x2.png"]',
  '["Carbono brillante","Cuero napa","Marcador M","Aluminio cepillado"]',
  '["BMW M3 F80","BMW M4 F82","BMW M2 F87"]',
  '{"aro":"Carbono brillante","agarres":"Cuero napa","costuras":"A elegir","marcador":"Tricolor M","levas":"Aluminio","pantalla_rpm":"No"}',
  'bmw,m3,m4,f80,f82,carbono,cuero,aluminio,diario',
  3,
  1
),
(
  'bmw-f80-f82-cuero-alcantara-neutro',
  'BMW',
  'bmw',
  'F80 / F82',
  'f80-f82',
  'Volante BMW M3 / M4 Cuero y Alcantara',
  'Version clasica del volante CDP para BMW M3 F80 y M4 F82. Aro en cuero perforado, agarres laterales en alcantara, marcador tricolor M y costuras blancas. Sin extras, solo lo esencial bien hecho. Una opcion equilibrada para los que buscan el acabado original mejorado.',
  'F82 clasico con cuero perforado y alcantara. Marcador M y costuras blancas.',
  'Cuero perforado + Alcantara',
  'Negro',
  0,
  679.00,
  NULL,
  'Clasico CDP',
  '4.8',
  'assets/img/gallery/F82/Cuero_alcantara/principal.png',
  '["assets/img/gallery/F82/Cuero_alcantara/principal.png","assets/img/gallery/F82/Cuero_alcantara/lateral.png","assets/img/gallery/F82/Cuero_alcantara/vista_x2.png"]',
  '["Cuero perforado","Alcantara","Costuras blancas","Marcador tricolor"]',
  '["BMW M3 F80","BMW M4 F82","BMW M2 F87"]',
  '{"aro":"Cuero perforado","agarres":"Alcantara","costuras":"Blanco","marcador":"Tricolor M","levas":"Sin levas","pantalla_rpm":"No"}',
  'bmw,m3,m4,f80,f82,cuero,alcantara,clasico,oem',
  4,
  1
),
(
  'bmw-f80-f82-cuero-perforado',
  'BMW',
  'bmw',
  'F80 / F82',
  'f80-f82',
  'Volante BMW M3 / M4 Cuero Perforado Full',
  'Volante BMW M3 F80 y M4 F82 fabricado integramente en cuero perforado, sin secciones de alcantara. Acabado uniforme, costuras a contraste y marcador superior tricolor M. Una opcion mas sobria, sin perder el toque deportivo. Levas en aluminio cepillado opcionales.',
  'F82 full cuero perforado. Sobrio y deportivo, sin alcantara.',
  'Cuero perforado',
  'Negro',
  0,
  629.00,
  NULL,
  'Disponible',
  '4.8',
  'assets/img/gallery/F82/Cuero_perforaa/principal.jpeg',
  '["assets/img/gallery/F82/Cuero_perforaa/principal.jpeg","assets/img/gallery/F82/Cuero_perforaa/lateral.jpeg","assets/img/gallery/F82/Cuero_perforaa/vista_x2.jpeg"]',
  '["Cuero perforado napa","Costuras a contraste","Marcador M","Aluminio (opcional)"]',
  '["BMW M3 F80","BMW M4 F82","BMW M2 F87"]',
  '{"aro":"Cuero perforado","agarres":"Cuero perforado","costuras":"A elegir","marcador":"Tricolor M","levas":"Sin levas / aluminio opcional","pantalla_rpm":"No"}',
  'bmw,m3,m4,f80,f82,cuero,perforado,sobrio',
  3,
  1
),
(
  'bmw-e46-carbono-rojo-sport',
  'BMW',
  'bmw',
  'E46',
  'e46',
  'Volante BMW E46 Carbono con Detalles Rojos',
  'Volante deportivo para BMW Serie 3 E46 y M3 E46 con aro de carbono brillante y detalles en rojo Sport. Agarres en cuero napa, costuras dobles en rojo y marcador superior tricolor M. Estilo agresivo para coches preparados o restomod, con el toque clasico del E46 pero materiales actuales.',
  'E46 con aro de carbono y detalles rojos. Costuras dobles y marcador M.',
  'Carbono + Cuero napa',
  'Negro / Rojo',
  0,
  689.00,
  NULL,
  'Sport',
  '4.9',
  'assets/img/gallery/E46/E46_Carbono_Rojo.png',
  '["assets/img/gallery/E46/E46_Carbono_Rojo.png"]',
  '["Carbono brillante","Cuero napa","Costuras dobles rojas","Marcador M"]',
  '["BMW Serie 3 E46","BMW M3 E46"]',
  '{"aro":"Carbono brillante","agarres":"Cuero napa","costuras":"Rojo","marcador":"Tricolor M","levas":"Sin levas","pantalla_rpm":"No"}',
  'bmw,e46,m3,carbono,rojo,sport,restomod',
  2,
  1
);
